config/routes.rb
Railsrobots::Application.routes.draw do
  

  
  get "reseterserver/resetme"

  get "helicopter/show"

  get "helicopter/new"

  get "helicopter/create"

  get "helicopter/update"

  get "helicopter/edit"

  get "helicopter/delete"

  get "helicopter/index"

  get "experiments_export/index", :as => :experiments_export
  post "experiments_export/export"

  get "upload/index", :as => :upload
  post "upload/upload_file"

  resources :participants
  resources :data_points  
  
  resources :robots
  post "robots/load_from_directory" => "robots#load_from_directory", :as => "load_from_directory"
  
  resources :matches do
    resources :results
  end
  
  resources :experiments do
    resources :robots
    resources :matches
  end
  post "experiments/:id/run" => "experiments#run", :as => "run_experiment"
  post "experiments/:id/reset" => "experiments#reset", :as => "reset_experiment"
  post "experiments/unstick" => "experiments#unstick", :as => "unstick_experiments"
  post "experiments/run_remaining" => "experiments#run_remaining", :as => "run_remaining_experiments"
  
  resources :results do
    resource :robot
  end

  get "home" => "home#index", :as => "home"
  

  root :to => 'home#index'

end

app/models/robot.rb
class Robot < ActiveRecord::Base
  attr_accessible :comments, :file_name, :inactive, :name
  
  validates :name, :file_name, :presence => true
  validates :name, :file_name, :uniqueness => { :case_sensitive => false }
  
  # Prevent the timestamp fields from being sent via JSON.  This is to stop problems with ActiveResource
  def as_json(options = {})
    super(:except => [:created_at, :updated_at])
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  # GET /robots
  # GET /robots.json
  def index
    if params[:file_name] == nil || params[:file_name].empty?
      @robots = Robot.all
    else
      @robots = Robot.where("file_name = ?", params[:file_name])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @robots }
    end
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
    @robot = Robot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @robot }
    end
  end

  # GET /robots/new
  # GET /robots/new.json
  def new
    @robot = Robot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @robot }
    end
  end

  # GET /robots/1/edit
  def edit
    @robot = Robot.find(params[:id])
  end

  # POST /robots
  # POST /robots.json
  def create
    @robot = Robot.new(params[:robot])

    respond_to do |format|
      if @robot.save
        format.html { redirect_to @robot, notice: 'Robot was successfully created.' }
        format.json { render json: @robot, status: :created, location: @robot }
      else
        format.html { render action: "new" }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /robots/1
  # PUT /robots/1.json
  def update
    @robot = Robot.find(params[:id])

    respond_to do |format|
      if @robot.update_attributes(params[:robot])
        format.html { redirect_to @robot, notice: 'Robot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy

    respond_to do |format|
      format.html { redirect_to robots_url }
      format.json { head :no_content }
    end
  end
  
  #--------------------------------------------------------------------------
  # New action to read the lib/rrobots/robots directory and create new
  # robot entries for any new .rb files found.
  def load_from_directory
    current_directory = Dir.pwd()
    
    Dir.chdir("lib/rrobots/robots")
    all_robots = Dir.glob("*.rb")
    
    @robots_added = 0
    all_robots.each do |robot_file|
      robot_query = Robot.where("file_name = ?", robot_file)
      if robot_query.length == 0
        robot = Robot.new()
        robot.inactive = false
        robot.file_name = robot_file
        robot.name = File.basename(robot_file, ".rb").gsub(/(?<=[A-Za-z])(?=[A-Z])/, ' ').gsub("_", " ")
        robot.save()
        @robots_added += 1
      end
    end    
    Dir.chdir(current_directory)
    
    respond_to do |format|
      format.html {redirect_to :back, notice: "Added #{@robots_added} robots."}
      format.json { head :no_content }
    end
  end
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/robots/_form.html.erb
<%= form_for(@robot) do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% @robot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :inactive %><br />
    <%= f.check_box :inactive %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing robot</h1>

<%= render 'form' %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<%= link_to 'Back', home_path %>

<p id="notice"><%= notice %></p>

<h1>Listing robots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>File name</th>
    <th>Comments</th>
    <th>Inactive</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @robots.each do |robot| %>
  <tr>
    <td><%= robot.name %></td>
    <td><%= robot.file_name %></td>
    <td><%= robot.comments %></td>
    <td><%= robot.inactive %></td>
    <td><%= link_to 'Show', robot %></td>
    <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
    <td><%= link_to 'Destroy', robot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New Robot', new_robot_path %>
<%= button_to "Load From Directory", {:action => "load_from_directory"}, :method => :load_from_directory%>

app/views/robots/new.html.erb
<h1>New robot</h1>

<%= render 'form' %>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @robot.name %>
</p>

<p>
  <b>File name:</b>
  <%= @robot.file_name %>
</p>

<p>
  <b>Comments:</b>
  <%= @robot.comments %>
</p>

<p>
  <b>Inactive:</b>
  <%= @robot.inactive %>
</p>


<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>