config/routes.rb
Railsrobots::Application.routes.draw do
  

  
  get "reseterserver/resetme"

  get "helicopter/show"

  get "helicopter/new"

  get "helicopter/create"

  get "helicopter/update"

  get "helicopter/edit"

  get "helicopter/delete"

  get "helicopter/index"

  get "experiments_export/index", :as => :experiments_export
  post "experiments_export/export"

  get "upload/index", :as => :upload
  post "upload/upload_file"

  resources :participants
  resources :data_points  
  
  resources :robots
  post "robots/load_from_directory" => "robots#load_from_directory", :as => "load_from_directory"
  
  resources :matches do
    resources :results
  end
  
  resources :experiments do
    resources :robots
    resources :matches
  end
  post "experiments/:id/run" => "experiments#run", :as => "run_experiment"
  post "experiments/:id/reset" => "experiments#reset", :as => "reset_experiment"
  post "experiments/unstick" => "experiments#unstick", :as => "unstick_experiments"
  post "experiments/run_remaining" => "experiments#run_remaining", :as => "run_remaining_experiments"
  
  resources :results do
    resource :robot
  end

  get "home" => "home#index", :as => "home"
  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Robots on Rails (Stevens Variant v1)</h1>
<p>This code has been altered from the RRobots baseline by adding adaptive behaviors, cargo agents, and helicopter agents.</p>
<%= link_to "Edit Robots", robots_path %>
<%= link_to "Edit Experiments", experiments_path %>
<%= link_to "Import Experiment Definition File", upload_path %>