config/routes.rb
Railsrobots::Application.routes.draw do
  

  
  get "reseterserver/resetme"

  get "helicopter/show"

  get "helicopter/new"

  get "helicopter/create"

  get "helicopter/update"

  get "helicopter/edit"

  get "helicopter/delete"

  get "helicopter/index"

  get "experiments_export/index", :as => :experiments_export
  post "experiments_export/export"

  get "upload/index", :as => :upload
  post "upload/upload_file"

  resources :participants
  resources :data_points  
  
  resources :robots
  post "robots/load_from_directory" => "robots#load_from_directory", :as => "load_from_directory"
  
  resources :matches do
    resources :results
  end
  
  resources :experiments do
    resources :robots
    resources :matches
  end
  post "experiments/:id/run" => "experiments#run", :as => "run_experiment"
  post "experiments/:id/reset" => "experiments#reset", :as => "reset_experiment"
  post "experiments/unstick" => "experiments#unstick", :as => "unstick_experiments"
  post "experiments/run_remaining" => "experiments#run_remaining", :as => "run_remaining_experiments"
  
  resources :results do
    resource :robot
  end

  get "home" => "home#index", :as => "home"
  

  root :to => 'home#index'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_many :participants, :dependent => :destroy
  has_many :robots, :through => :participants
  has_many :results, :as => :parent, :dependent => :destroy
  has_many :matches, :dependent => :destroy
  
  
  attr_accessible :match_count, :name, :notes, :participants_attributes, :running, :completed, :calculating_summary
  
  validates :name, :match_count, :presence => true
  validates :name, :uniqueness => { :case_sensitive => false }
  
  accepts_nested_attributes_for :participants, :allow_destroy => true,
                                :reject_if => proc { |p| p["robot_id"].blank?}
  
  
  # Prevent the timestamp fields from being sent via JSON.  This is to stop problems with ActiveResource
  def as_json(options = {})
    super(:except => [:created_at, :updated_at])
  end
  
  # Resets experiment data.  Optionally force reset even if the experiment still appears to be running.  Returns a status message.
  def reset(force = false)
     if self.running? and !force
       "Experiment is running.  Wait until it has finished."
     else
       self.matches.clear()
       self.results.clear()
       self.running = false
       self.completed = false
       self.calculating_summary = false
       self.save()
       return "Experiment data reset."
     end
  end
  
  # This is a special method just to keep the code DRY, so this query is only written out in once
  # place.
  def self.get_summary_query(experiment_id)
    return "SELECT r.robot_id, d.data_key,
                  MIN(d.data_value) AS min_data_value, 
                  MAX(d.data_value) AS max_data_value, 
                  AVG(d.data_value) AS avg_data_value, 
                  SUM(d.data_value) AS tot_data_value 
          FROM data_points AS d 
          INNER JOIN results AS r ON r.id = d.parent_id AND d.parent_type = 'Result'   
          INNER JOIN matches AS m ON m.id = r.parent_id AND r.parent_type = 'Match' 
          INNER JOIN experiments AS e ON e.id = m.experiment_id 
          WHERE e.id = #{experiment_id} 
          GROUP BY r.robot_id, d.data_key"
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.json
  def index
    if params[:summary] and params[:experiment_id] != nil
      @experiments = DataPoint.find_by_sql(Experiment.get_summary_query(params[:experiment_id]))  
    else
      @experiments = Experiment.includes(:participants, :results => [:data_points, :robot]).all()
    end
          
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @experiment = Experiment.includes(:participants, :results => [:data_points, :robot]).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.json
  def new
    @experiment = Experiment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end
  
  
  # New action to run experiments
  def run
    require_relative '../../lib/workers/experiment_worker.rb'
    worker = ExperimentWorker.new()
    
    # The worker class uses ActiveResource to write its data back in order to be thread safe.  Have to give it the site
    # URL to use, since we shouldn't assume that we're local host port 3000.
    worker.callback_site = "http://localhost:" + request.port.to_s() #request.protocol + request.host + ":" + request.port.to_s()

    worker.experiment_id = params[:id].to_i() 
    worker.run()
    
    respond_to do |format|
      format.html {redirect_to :back, notice: worker.status_message}
      format.json {head :no_content}
    end
  end
  
  
  # New action to reset the results of an experiment
  def reset
    @experiment = Experiment.find(params[:id])
    status_message = @experiment.reset()
    
    respond_to do |format|
      format.html {redirect_to :back, notice: status_message}
      format.json {head :no_content}
    end
  end
  
  
  # New action to deal with crashes.
  def unstick
    experiments = Experiment.where("running = 't' OR calculating_summary = 't'")
    
    count = experiments.count
    experiments.each do |experiment|
      experiment.reset(true)
    end
    
    respond_to do |format|
      format.html {redirect_to :back, notice: "Force-reset #{count} Experiment(s)."}
      format.json {head :no_content}
    end
  end
  
  
  # New action to deal with restarting after crashes
  def run_remaining
    require_relative '../../lib/workers/experiment_batch_worker.rb'
    worker = ExperimentBatchWorker.new()
    
    # The worker class uses ActiveResource to write its data back in order to be thread safe.  Have to give it the site
    # URL to use, since we shouldn't assume that we're local host port 3000.
    worker.callback_site = "http://localhost:" + request.port.to_s() #request.protocol + request.host + ":" + request.port.to_s()
    
    worker.experiment_ids = Experiment.where("completed = 'f' OR completed IS NULL").map {|experiment| experiment.id}
    
    worker.run()
    
    respond_to do |format|
      format.html {redirect_to :back, notice: worker.status_message}
      format.json {head :no_content}
    end 
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<% @experiment.participants.build %>
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :match_count %><br />
    <%= f.number_field :match_count %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <h2>Participants</h2>
  <%= render :partial => 'participants/form',
  			 :locals => {:form => f} %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<%= link_to 'Back', home_path %>
<p id="notice"><%= notice %></p>
<h1>Listing experiments</h1>

<%= button_to "Unstick Experiments", {:action => "unstick"}, :confirm => "Only do this if you're sure no experiments are actually running.  Are you sure?", :method => :unstick %>
<%= button_to "Run Remaining Experiments", {:action => "run_remaining"} %>

<%
# We need to calculate the maximum number of robots involved in any one experiment in order to determine
# how many extra columns we'll need in the table.
@max_robots = 0
@experiments.each do |experiment|
	@max_robots = [@max_robots, experiment.participants.length].max()
end

# Make sure we always have at least one column.
@max_robots = [@max_robots, 1].max()

%>

<table border=1>
  <tr>
    <th>Name</th>
    <th>Match count</th>
    <th>Notes</th>
    
    <% @max_robots.times do %>
    	<th></th>
    <% end %>
    
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>




<% @experiments.each do |experiment| %>
  <tr>
    <td><%= experiment.name %></td>
    <td><%= experiment.match_count %></td>
    <td><%= experiment.notes %></td>

	<% if experiment.completed
		# Experiment is completed, display the participants, ranked in winning order.
		
		# Sort the results records by wins descending
		results_array = experiment.results.sort_by do |individual_result|
			experiment.match_count - (individual_result.get_data_point("tot_wins") || 0)
		end
		%>

		<% @max_robots.times do |i| %>
	    <td>
	    	<% if i < results_array.length %>
	    		<%= results_array[i].robot.name %>
	    		<br />
	    		(<%= results_array[i].get_data_point("tot_wins") || 0 %>W, <%= results_array[i].get_data_point("tot_losses") || 0 %>L, <%= results_array[i].get_data_point("tot_draws") || 0 %>D)
	    	<% end %>
	    </td>
	    <% end %>
	    
	<% elsif experiment.running %>
		<td colspan=<%= @max_robots %>>Running, <%= experiment.matches.count %> / <%= experiment.match_count %></td>
		
	<% elsif experiment.calculating_summary %>	
		<td colspan=<%= @max_robots %>>Calculating Summary Results</td>
		
	<% else %>
		<td colspan=<%= @max_robots %>>Ready</td>
	<% end %>
    
    <td><%= link_to 'Show', experiment %></td>
    <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
    <td><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= button_to "Run", {:action => "run", :id => experiment.id}%></td>
    <td><%= button_to "Reset", {:action => "reset", :id => experiment.id}, :confirm => "Are you sure?", :method => :reset%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Experiment', new_experiment_path %> | <%= link_to "Export Results", experiments_export_path %>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @experiment.name %>
</p>

<p>
  <b>Match count:</b>
  <%= @experiment.match_count %>
</p>

<p>
  <b>Notes:</b>
  <%= @experiment.notes %>
</p>

<h2>Participants</h2>
<%= render @experiment.participants %>

<% if @experiment.running? %>
<h2>Experiment Running.  <%= @experiment.matches.count %> Matches Completed.</h2>
<% end %>

<% if @experiment.calculating_summary? %>
<h2>Experiment is currently calculating summary results.</h2>
<% end %>


<% if @experiment.completed? %>
<!-- TODO: Refactor this into a separate file -->
<h2>Experiment Results</h2>
<table border="1">
	<tr>
		<th>Robot</th>
		<th>Total Wins</th>
		<th>Total Losses</th>
		<th>Total Draws</th>
		<th>Average Remaining Energy</th>
		<th>Average Survival Time</th>
		<th>Average Kills</th>
		<th>Average Damage Given</th>
	</tr>
  <% @experiment.results.each do |result| %>
  <tr>
  	<td><%= result.robot.name %></td>
  	<td><%= result.get_data_point("tot_wins") || 0 %></td>
  	<td><%= result.get_data_point("tot_losses") || 0 %></td>
  	<td><%= result.get_data_point("tot_draws") || 0 %></td>
  	<td><%= (result.get_data_point("avg_remaining_energy") || 0).round(2) %></td>
  	<td><%= (result.get_data_point("avg_survival_time") || 0).round(2) %></td>
  	<td><%= (result.get_data_point("avg_kills") || 0).round(2) %></td>
  	<td><%= (result.get_data_point("avg_damage_given") || 0).round(2) %></td>
  </tr>
  <% end %>
</table>
<br>
<% end %>

<%= button_to "Run", {:action => "run", :id => @experiment.id}%>
<%= button_to "Reset", {:action => "reset", :id => @experiment.id}, :confirm => "Are you sure?", :method => :reset%>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>