config/routes.rb
Railsrobots::Application.routes.draw do
  

  
  get "reseterserver/resetme"

  get "helicopter/show"

  get "helicopter/new"

  get "helicopter/create"

  get "helicopter/update"

  get "helicopter/edit"

  get "helicopter/delete"

  get "helicopter/index"

  get "experiments_export/index", :as => :experiments_export
  post "experiments_export/export"

  get "upload/index", :as => :upload
  post "upload/upload_file"

  resources :participants
  resources :data_points  
  
  resources :robots
  post "robots/load_from_directory" => "robots#load_from_directory", :as => "load_from_directory"
  
  resources :matches do
    resources :results
  end
  
  resources :experiments do
    resources :robots
    resources :matches
  end
  post "experiments/:id/run" => "experiments#run", :as => "run_experiment"
  post "experiments/:id/reset" => "experiments#reset", :as => "reset_experiment"
  post "experiments/unstick" => "experiments#unstick", :as => "unstick_experiments"
  post "experiments/run_remaining" => "experiments#run_remaining", :as => "run_remaining_experiments"
  
  resources :results do
    resource :robot
  end

  get "home" => "home#index", :as => "home"
  

  root :to => 'home#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :experiment
  has_many :results, :as => :parent, :dependent => :destroy
  
  attr_accessible :duration
  
  attr_accessible :experiment_id
  
  # Prevent the timestamp fields from being sent via JSON.  This is to stop problems with ActiveResource
  def as_json(options = {})
    super(:except => [:created_at, :updated_at])
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :experiment %><br />
    <%= f.text_field :experiment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Duration</th>
    <th>Experiment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.duration %></td>
    <td><%= match.experiment %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Duration:</b>
  <%= @match.duration %>
</p>

<p>
  <b>Experiment:</b>
  <%= @match.experiment %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>